// exporters.js — turn fetched site data into files a student imports into Rhino.
//
// All formats are plain text, hand-written, zero dependencies:
//   terrain.obj    — DEM grid → triangulated mesh, in local metres
//   contours.dxf   — marching-squares contour polylines from the same grid
//   boundary.dxf   — the EPA site boundary as closed polylines, in local metres
//   boundary.geojson — the boundary in WGS84 for any GIS tool
//   <site>.epw     — generated EnergyPlus weather file (8760 rows) for Ladybug
//
// Local-metre coordinates share one origin (the bbox SW corner) and one
// projection, so terrain + contours + boundary all line up when imported together.

import { makeProjector } from "./geo.js";

// Shared origin for everything in a site's export bundle: SW corner of the grid bbox.
function originFor(bbox) {
  const [w, s] = bbox;
  return { refLon: w, refLat: s, proj: makeProjector(s, w) };
}

// --- terrain.obj -----------------------------------------------------------

export function terrainOBJ(topo) {
  const { grid, n, bbox } = topo;
  const { proj } = originFor(bbox);
  const [w, s, e, nth] = bbox;
  const lines = [
    "# Site terrain mesh — generated by Site Analyzer",
    "# Units: metres. Origin: SW corner of site bounding box. +X east, +Y north, +Z up.",
    `# Grid: ${n} x ${n} samples from USGS 3DEP.`,
    "o site_terrain"
  ];
  // Vertices, row-major (south→north, west→east).
  for (let r = 0; r < n; r++) {
    for (let c = 0; c < n; c++) {
      const lon = w + ((e - w) * c) / (n - 1);
      const lat = s + ((nth - s) * r) / (n - 1);
      const [x, y] = proj.toLocal(lon, lat);
      lines.push(`v ${x.toFixed(3)} ${y.toFixed(3)} ${grid[r][c].toFixed(3)}`);
    }
  }
  // Two triangles per grid cell (OBJ is 1-indexed).
  const idx = (r, c) => r * n + c + 1;
  for (let r = 0; r < n - 1; r++) {
    for (let c = 0; c < n - 1; c++) {
      const a = idx(r, c);
      const b = idx(r, c + 1);
      const d = idx(r + 1, c);
      const e2 = idx(r + 1, c + 1);
      lines.push(`f ${a} ${b} ${e2}`);
      lines.push(`f ${a} ${e2} ${d}`);
    }
  }
  return lines.join("\n") + "\n";
}

// --- contours.dxf ----------------------------------------------------------

// Marching squares over the elevation grid → contour line segments at each
// interval, written as DXF LINE entities (layer per elevation).
export function contoursDXF(topo, interval) {
  const { grid, n, bbox } = topo;
  const { proj } = originFor(bbox);
  const [w, s, e, nth] = bbox;
  let min = Infinity, max = -Infinity;
  for (const row of grid) for (const v of row) {
    if (v < min) min = v;
    if (v > max) max = v;
  }
  if (!interval) interval = niceInterval(max - min);

  const xy = (c, r) => {
    const lon = w + ((e - w) * c) / (n - 1);
    const lat = s + ((nth - s) * r) / (n - 1);
    return proj.toLocal(lon, lat);
  };

  const segments = []; // {level, x1,y1,x2,y2}
  const start = Math.ceil(min / interval) * interval;
  for (let level = start; level < max; level += interval) {
    for (let r = 0; r < n - 1; r++) {
      for (let c = 0; c < n - 1; c++) {
        // Corner values: bottom-left, bottom-right, top-right, top-left.
        const corners = [grid[r][c], grid[r][c + 1], grid[r + 1][c + 1], grid[r + 1][c]];
        const crossings = [];
        const edges = [
          [corners[0], corners[1], [c, r], [c + 1, r]],
          [corners[1], corners[2], [c + 1, r], [c + 1, r + 1]],
          [corners[2], corners[3], [c + 1, r + 1], [c, r + 1]],
          [corners[3], corners[0], [c, r + 1], [c, r]]
        ];
        for (const [va, vb, pa, pb] of edges) {
          if ((va - level) * (vb - level) < 0) {
            const t = (level - va) / (vb - va);
            crossings.push([pa[0] + (pb[0] - pa[0]) * t, pa[1] + (pb[1] - pa[1]) * t]);
          }
        }
        if (crossings.length === 2) {
          const [p1, p2] = crossings;
          const [x1, y1] = xy(p1[0], p1[1]);
          const [x2, y2] = xy(p2[0], p2[1]);
          segments.push({ level, x1, y1, x2, y2 });
        }
      }
    }
  }

  const ents = segments
    .map(
      (g) =>
        `0\nLINE\n8\nCONTOUR_${Math.round(g.level)}\n10\n${g.x1.toFixed(3)}\n20\n${g.y1.toFixed(
          3
        )}\n30\n${g.level.toFixed(3)}\n11\n${g.x2.toFixed(3)}\n21\n${g.y2.toFixed(3)}\n31\n${g.level.toFixed(3)}`
    )
    .join("\n");
  return dxfWrap(ents);
}

// --- boundary.dxf / .geojson ----------------------------------------------

export function boundaryDXF(boundaryGeoJSON, bbox) {
  if (!boundaryGeoJSON) return dxfWrap("");
  const { proj } = originFor(bbox);
  const polys = boundaryGeoJSON.type === "MultiPolygon" ? boundaryGeoJSON.coordinates : [boundaryGeoJSON.coordinates];
  const ents = [];
  for (const poly of polys) {
    for (const ring of poly) {
      const verts = ring.map(([lon, lat]) => proj.toLocal(lon, lat));
      // LWPOLYLINE, closed.
      let e = `0\nLWPOLYLINE\n8\nSITE_BOUNDARY\n90\n${verts.length}\n70\n1`;
      for (const [x, y] of verts) e += `\n10\n${x.toFixed(3)}\n20\n${y.toFixed(3)}`;
      ents.push(e);
    }
  }
  return dxfWrap(ents.join("\n"));
}

export function boundaryGeoJSON(site) {
  return JSON.stringify(
    {
      type: "FeatureCollection",
      features: [
        {
          type: "Feature",
          properties: { name: site.name, epaId: site.epaId, status: site.status, areaAcres: site.areaAcres },
          geometry: site.boundary
        }
      ]
    },
    null,
    2
  );
}

// --- EPW -------------------------------------------------------------------

// Generate a valid EnergyPlus Weather file from the Open-Meteo hourly year.
// 8 header lines + 8760 data rows. Fields we don't have use EPW missing codes,
// so Ladybug/EnergyPlus read it cleanly but a student can see what's measured vs not.
export function climateEPW(climate, site) {
  const n = climate.time.length;
  const loc = [
    "LOCATION",
    (site?.name || "Site").replace(/,/g, " "),
    site?.state || "-",
    "USA",
    "Open-Meteo ERA5 (generated)",
    "000000",
    climate.lat.toFixed(4),
    climate.lon.toFixed(4),
    climate.tzOffsetHours.toFixed(1),
    (climate.elevation ?? 0).toFixed(1)
  ].join(",");

  const header = [
    loc,
    "DESIGN CONDITIONS,0",
    "TYPICAL/EXTREME PERIODS,0",
    "GROUND TEMPERATURES,0",
    "HOLIDAYS/DAYLIGHT SAVINGS,No,0,0,0",
    "COMMENTS 1,Generated by Site Analyzer from Open-Meteo ERA5 reanalysis. NOT a measured TMY — reanalysis at ~25km resolution. Use for relative/early-stage analysis; verify against a measured station file for final work.",
    `COMMENTS 2,Source year ${climate.year}. Measured fields: dry-bulb temp, RH, dew point, wind speed/direction, station pressure, GHI, DNI, DHI, total sky cover. Other fields are EPW missing codes.`,
    `DATA PERIODS,1,1,Data,Sunday,1/1,12/31`
  ];

  const MISS = {
    extHorzIR: "9999", extDirNorm: "9999",
    ghIllum: "999999", dnIllum: "999999", dhIllum: "999999", zenLum: "9999",
    visibility: "9999", ceiling: "99999", precipWater: "999",
    aerosol: ".999", snow: "999", daysSinceSnow: "99",
    albedo: "999", rainDepth: "999", rainHours: "99"
  };

  const rows = [];
  for (let i = 0; i < n; i++) {
    const t = climate.time[i]; // "YYYY-MM-DDTHH:MM"
    const year = t.slice(0, 4);
    const month = String(Number(t.slice(5, 7)));
    const day = String(Number(t.slice(8, 10)));
    // EPW is strictly 8760 rows — drop the leap day so leap years stay standard.
    if (month === "2" && day === "29") continue;
    let hour = Number(t.slice(11, 13)) + 1; // EPW hours are 1..24
    const ghi = num(climate.ghi[i]);
    const dni = num(climate.dni[i]);
    const dhi = num(climate.dhi[i]);
    rows.push([
      year, month, day, hour, "0", // datetime + minute
      "Generated from Open-Meteo ERA5; ?9?9?9?9E0?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9*9*9*9?9?9", // uncertainty flags
      fix(climate.tempC[i], 1, "99.9"), // dry bulb
      fix(climate.dewC[i], 1, "99.9"), // dew point
      fix(climate.rh[i], 0, "999"), // RH
      fix(mul(climate.pressure[i], 100), 0, "999999"), // station pressure Pa (hPa→Pa)
      MISS.extHorzIR, MISS.extDirNorm,
      "9999", // horizontal infrared from sky (missing)
      fix(ghi, 0, "9999"), // global horizontal radiation
      fix(dni, 0, "9999"), // direct normal radiation
      fix(dhi, 0, "9999"), // diffuse horizontal radiation
      MISS.ghIllum, MISS.dnIllum, MISS.dhIllum, MISS.zenLum,
      fix(climate.windDir[i], 0, "999"), // wind direction
      fix(climate.windSpeed[i], 1, "999"), // wind speed
      fix(div(climate.cloud[i], 10), 0, "99"), // total sky cover (0-10)
      fix(div(climate.cloud[i], 10), 0, "99"), // opaque sky cover (0-10)
      MISS.visibility, MISS.ceiling,
      "9", // present weather observation
      "999999999", // present weather codes
      MISS.precipWater, MISS.aerosol, MISS.snow, MISS.daysSinceSnow,
      MISS.albedo, MISS.rainDepth, MISS.rainHours
    ].join(","));
  }
  return header.join("\n") + "\n" + rows.join("\n") + "\n";
}

// --- helpers ---------------------------------------------------------------

function dxfWrap(entities) {
  return (
    "0\nSECTION\n2\nHEADER\n0\nENDSEC\n" +
    "0\nSECTION\n2\nENTITIES\n" +
    (entities ? entities + "\n" : "") +
    "0\nENDSEC\n0\nEOF\n"
  );
}

function niceInterval(range) {
  if (!range || range <= 0) return 1;
  const raw = range / 10;
  const mag = Math.pow(10, Math.floor(Math.log10(raw)));
  const norm = raw / mag;
  const step = norm < 1.5 ? 1 : norm < 3 ? 2 : norm < 7 ? 5 : 10;
  return step * mag;
}

const num = (v) => (v == null || Number.isNaN(v) ? null : Number(v));
const mul = (v, k) => (num(v) == null ? null : v * k);
const div = (v, k) => (num(v) == null ? null : v / k);
function fix(v, dp, missing) {
  const x = num(v);
  return x == null ? missing : x.toFixed(dp);
}
