// exporters.ts — turn fetched site data into files a student imports into Rhino.
//
// Ported from TOOLS/site-analyzer/web/exporters.js. All formats are plain text,
// hand-written, zero dependencies → they run fine in the browser, so the Toolkit
// generates every download CLIENT-SIDE from the analyze payload (no server call,
// no Vercel 60s exposure, free for anonymous visitors).
//
//   terrainOBJ       — DEM grid → triangulated mesh, in local metres
//   contoursDXF      — marching-squares contour polylines from the same grid
//   boundaryDXF      — the EPA site boundary as closed polylines, in local metres
//   boundaryGeoJSON  — the boundary in WGS84 for any GIS tool
//   climateEPW       — generated EnergyPlus weather file (8760 rows) for Ladybug
//
// Local-metre coordinates share one origin (the bbox SW corner) and one
// projection, so terrain + contours + boundary all line up when imported together.

import { makeProjector } from "./geo";
import type { ClimateRaw, Site, Topo } from "./datasources";

// Shared origin for everything in a site's export bundle: SW corner of the grid bbox.
function originFor(bbox: number[]) {
  const [w, s] = bbox;
  return { refLon: w, refLat: s, proj: makeProjector(s, w) };
}

// --- terrain.obj -----------------------------------------------------------

export function terrainOBJ(topo: Topo): string {
  const { grid, n, bbox, missingMask } = topo;
  const { proj } = originFor(bbox);
  const [w, s, e, nth] = bbox;
  let fab = 0;
  if (missingMask) for (const row of missingMask) for (const v of row) if (v) fab++;
  const lines = [
    "# Site terrain mesh — generated by Surveyor (All Means Works)",
    "# Units: metres. Origin (0,0,0) = SW corner of the site bounding box. +X east, +Y north, +Z up.",
    `# Georeference: origin at lat ${s.toFixed(6)}, lon ${w.toFixed(6)} (WGS84), equirectangular local projection.`,
    `# Grid: ${n} x ${n} USGS 3DEP samples${
      fab ? `; ${fab} cell(s) were outside coverage and their faces are OMITTED (no fabricated ground)` : ""
    }.`,
    "o site_terrain"
  ];
  // Vertices, row-major (south→north, west→east). All vertices are written so the
  // index math stays simple; fabricated cells just don't get faces.
  for (let r = 0; r < n; r++) {
    for (let c = 0; c < n; c++) {
      const lon = w + ((e - w) * c) / (n - 1);
      const lat = s + ((nth - s) * r) / (n - 1);
      const [x, y] = proj.toLocal(lon, lat);
      lines.push(`v ${x.toFixed(3)} ${y.toFixed(3)} ${grid[r][c].toFixed(3)}`);
    }
  }
  // Two triangles per grid cell (OBJ is 1-indexed). Skip any cell touching a
  // back-filled vertex so the exported mesh contains only measured ground.
  const idx = (r: number, c: number) => r * n + c + 1;
  const fabAt = (r: number, c: number) => !!missingMask?.[r]?.[c];
  for (let r = 0; r < n - 1; r++) {
    for (let c = 0; c < n - 1; c++) {
      if (fabAt(r, c) || fabAt(r, c + 1) || fabAt(r + 1, c) || fabAt(r + 1, c + 1)) continue;
      const a = idx(r, c);
      const b = idx(r, c + 1);
      const d = idx(r + 1, c);
      const e2 = idx(r + 1, c + 1);
      lines.push(`f ${a} ${b} ${e2}`);
      lines.push(`f ${a} ${e2} ${d}`);
    }
  }
  return lines.join("\n") + "\n";
}

// --- contours.dxf ----------------------------------------------------------

// Marching squares over the elevation grid → contour line segments at each
// interval, written as DXF LINE entities (layer per elevation).
export function contoursDXF(topo: Topo, interval = 0): string {
  const { grid, n, bbox } = topo;
  const { proj } = originFor(bbox);
  const [w, s, e, nth] = bbox;
  let min = Infinity, max = -Infinity;
  for (const row of grid) for (const v of row) {
    if (v < min) min = v;
    if (v > max) max = v;
  }
  if (!interval) interval = niceInterval(max - min);

  const xy = (c: number, r: number): [number, number] => {
    const lon = w + ((e - w) * c) / (n - 1);
    const lat = s + ((nth - s) * r) / (n - 1);
    return proj.toLocal(lon, lat);
  };

  const segments: { level: number; x1: number; y1: number; x2: number; y2: number }[] = [];
  const start = Math.ceil(min / interval) * interval;
  for (let level = start; level < max; level += interval) {
    for (let r = 0; r < n - 1; r++) {
      for (let c = 0; c < n - 1; c++) {
        // Corner values: bottom-left, bottom-right, top-right, top-left.
        const corners = [grid[r][c], grid[r][c + 1], grid[r + 1][c + 1], grid[r + 1][c]];
        const crossings: [number, number][] = [];
        const edges: [number, number, [number, number], [number, number]][] = [
          [corners[0], corners[1], [c, r], [c + 1, r]],
          [corners[1], corners[2], [c + 1, r], [c + 1, r + 1]],
          [corners[2], corners[3], [c + 1, r + 1], [c, r + 1]],
          [corners[3], corners[0], [c, r + 1], [c, r]]
        ];
        for (const [va, vb, pa, pb] of edges) {
          if ((va - level) * (vb - level) < 0) {
            const t = (level - va) / (vb - va);
            crossings.push([pa[0] + (pb[0] - pa[0]) * t, pa[1] + (pb[1] - pa[1]) * t]);
          }
        }
        if (crossings.length === 2) {
          const [p1, p2] = crossings;
          const [x1, y1] = xy(p1[0], p1[1]);
          const [x2, y2] = xy(p2[0], p2[1]);
          segments.push({ level, x1, y1, x2, y2 });
        }
      }
    }
  }

  // Chain the marching-squares segments into joined polylines per level — far more
  // usable in Rhino than thousands of disconnected 2-point LINE entities.
  const byLevel = new Map<number, Seg[]>();
  for (const g of segments) {
    const arr = byLevel.get(g.level);
    if (arr) arr.push(g);
    else byLevel.set(g.level, [g]);
  }
  const ents: string[] = [];
  for (const [level, segs] of byLevel) {
    for (const chain of chainSegments(segs)) {
      if (chain.length < 2) continue;
      const closed = chain.length > 2 && ptKey(chain[0]) === ptKey(chain[chain.length - 1]);
      const verts = closed ? chain.slice(0, -1) : chain;
      // LWPOLYLINE with constant elevation (group 38) = a true contour at this level.
      let ent = `0\nLWPOLYLINE\n8\nCONTOUR_${Math.round(level)}\n90\n${verts.length}\n70\n${closed ? 1 : 0}\n38\n${level.toFixed(3)}`;
      for (const [x, y] of verts) ent += `\n10\n${x.toFixed(3)}\n20\n${y.toFixed(3)}`;
      ents.push(ent);
    }
  }
  return dxfWrap(ents.join("\n"));
}

type Seg = { level: number; x1: number; y1: number; x2: number; y2: number };

// Quantised point key (1 cm) for matching segment endpoints.
function ptKey(p: number[]): string {
  return `${Math.round(p[0] * 100)},${Math.round(p[1] * 100)}`;
}

// Greedily chain 2-point segments into polylines by matching endpoints.
function chainSegments(segs: Seg[]): number[][][] {
  const used = new Array(segs.length).fill(false);
  const adj = new Map<string, { i: number; other: number[] }[]>();
  const push = (k: string, v: { i: number; other: number[] }) => {
    const a = adj.get(k);
    if (a) a.push(v);
    else adj.set(k, [v]);
  };
  segs.forEach((s, i) => {
    push(ptKey([s.x1, s.y1]), { i, other: [s.x2, s.y2] });
    push(ptKey([s.x2, s.y2]), { i, other: [s.x1, s.y1] });
  });
  const extend = (chain: number[][], end: "head" | "tail") => {
    for (;;) {
      const pt = end === "tail" ? chain[chain.length - 1] : chain[0];
      const next = (adj.get(ptKey(pt)) || []).find((c) => !used[c.i]);
      if (!next) break;
      used[next.i] = true;
      if (end === "tail") chain.push(next.other);
      else chain.unshift(next.other);
    }
  };
  const chains: number[][][] = [];
  for (let i = 0; i < segs.length; i++) {
    if (used[i]) continue;
    used[i] = true;
    const chain: number[][] = [
      [segs[i].x1, segs[i].y1],
      [segs[i].x2, segs[i].y2]
    ];
    extend(chain, "tail");
    extend(chain, "head");
    chains.push(chain);
  }
  return chains;
}

// --- boundary.dxf / .geojson ----------------------------------------------

export function boundaryDXF(
  boundaryGeoJSON: { type: string; coordinates: any } | null,
  bbox: number[]
): string {
  if (!boundaryGeoJSON) return dxfWrap("");
  const { proj } = originFor(bbox);
  const polys =
    boundaryGeoJSON.type === "MultiPolygon"
      ? boundaryGeoJSON.coordinates
      : [boundaryGeoJSON.coordinates];
  const ents: string[] = [];
  for (const poly of polys) {
    for (const ring of poly) {
      const verts = ring.map(([lon, lat]: [number, number]) => proj.toLocal(lon, lat));
      // LWPOLYLINE, closed.
      let e = `0\nLWPOLYLINE\n8\nSITE_BOUNDARY\n90\n${verts.length}\n70\n1`;
      for (const [x, y] of verts) e += `\n10\n${x.toFixed(3)}\n20\n${y.toFixed(3)}`;
      ents.push(e);
    }
  }
  return dxfWrap(ents.join("\n"));
}

export function boundaryGeoJSON(site: Site): string {
  return JSON.stringify(
    {
      type: "FeatureCollection",
      features: [
        {
          type: "Feature",
          properties: {
            name: site.name,
            epaId: site.epaId,
            status: site.status,
            areaAcres: site.areaAcres
          },
          geometry: site.boundary
        }
      ]
    },
    null,
    2
  );
}

// --- EPW -------------------------------------------------------------------

// Generate a valid EnergyPlus Weather file from the Open-Meteo hourly year.
// 8 header lines + 8760 data rows. Fields we don't have use EPW missing codes,
// so Ladybug/EnergyPlus read it cleanly but a student can see what's measured vs not.
export function climateEPW(climate: ClimateRaw, site?: Partial<Site>): string {
  const n = climate.time.length;
  const loc = [
    "LOCATION",
    (site?.name || "Site").replace(/,/g, " "),
    site?.state || "-",
    "USA",
    "Open-Meteo ERA5 (generated)",
    "000000",
    climate.lat.toFixed(4),
    climate.lon.toFixed(4),
    climate.tzOffsetHours.toFixed(1),
    (climate.elevation ?? 0).toFixed(1)
  ].join(",");

  // EPW wants the real weekday of Jan 1 for the source year, not a hardcoded one.
  const startDay = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"][
    new Date(Date.UTC(climate.year, 0, 1)).getUTCDay()
  ];
  const header = [
    loc,
    "DESIGN CONDITIONS,0",
    "TYPICAL/EXTREME PERIODS,0",
    "GROUND TEMPERATURES,0",
    "HOLIDAYS/DAYLIGHT SAVINGS,No,0,0,0",
    "COMMENTS 1,Generated by Surveyor from Open-Meteo ERA5 reanalysis (~25 km). NOT a measured TMY — reanalysis modelled values; use for relative/early-stage analysis and verify against a measured station file for final work.",
    `COMMENTS 2,Source year ${climate.year}. Modelled fields: dry-bulb temp, RH, dew point, wind speed/direction, station pressure, GHI, DNI, DHI, total sky cover. Other fields are EPW missing codes.`,
    `DATA PERIODS,1,1,Data,${startDay},1/1,12/31`
  ];

  const MISS = {
    extHorzIR: "9999", extDirNorm: "9999",
    ghIllum: "999999", dnIllum: "999999", dhIllum: "999999", zenLum: "9999",
    visibility: "9999", ceiling: "99999", precipWater: "999",
    aerosol: ".999", snow: "999", daysSinceSnow: "99",
    albedo: "999", rainDepth: "999", rainHours: "99"
  };

  const rows: string[] = [];
  for (let i = 0; i < n; i++) {
    const t = climate.time[i]; // "YYYY-MM-DDTHH:MM"
    const year = t.slice(0, 4);
    const month = String(Number(t.slice(5, 7)));
    const day = String(Number(t.slice(8, 10)));
    // EPW is strictly 8760 rows — drop the leap day so leap years stay standard.
    if (month === "2" && day === "29") continue;
    const hour = Number(t.slice(11, 13)) + 1; // EPW hours are 1..24
    const ghi = num(climate.ghi[i]);
    const dni = num(climate.dni[i]);
    const dhi = num(climate.dhi[i]);
    rows.push(
      [
        year, month, day, hour, "0", // datetime + minute
        "Generated from Open-Meteo ERA5; ?9?9?9?9E0?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9*9*9*9?9?9", // uncertainty flags
        fix(climate.tempC[i], 1, "99.9"), // dry bulb
        fix(climate.dewC[i], 1, "99.9"), // dew point
        fix(climate.rh[i], 0, "999"), // RH
        fix(mul(climate.pressure[i], 100), 0, "999999"), // station pressure Pa (hPa→Pa)
        MISS.extHorzIR, MISS.extDirNorm,
        "9999", // horizontal infrared from sky (missing)
        fix(ghi, 0, "9999"), // global horizontal radiation
        fix(dni, 0, "9999"), // direct normal radiation
        fix(dhi, 0, "9999"), // diffuse horizontal radiation
        MISS.ghIllum, MISS.dnIllum, MISS.dhIllum, MISS.zenLum,
        fix(climate.windDir[i], 0, "999"), // wind direction
        fix(climate.windSpeed[i], 1, "999"), // wind speed
        fix(div(climate.cloud[i], 10), 0, "99"), // total sky cover (0-10)
        fix(div(climate.cloud[i], 10), 0, "99"), // opaque sky cover (0-10)
        MISS.visibility, MISS.ceiling,
        "9", // present weather observation
        "999999999", // present weather codes
        MISS.precipWater, MISS.aerosol, MISS.snow, MISS.daysSinceSnow,
        MISS.albedo, MISS.rainDepth, MISS.rainHours
      ].join(",")
    );
  }
  return header.join("\n") + "\n" + rows.join("\n") + "\n";
}

// --- helpers ---------------------------------------------------------------

function dxfWrap(entities: string): string {
  return (
    // $INSUNITS = 6 → metres, so Rhino/CAD imports at the right scale even if the
    // target document isn't already in metres.
    "0\nSECTION\n2\nHEADER\n9\n$INSUNITS\n70\n6\n0\nENDSEC\n" +
    "0\nSECTION\n2\nENTITIES\n" +
    (entities ? entities + "\n" : "") +
    "0\nENDSEC\n0\nEOF\n"
  );
}

function niceInterval(range: number): number {
  if (!range || range <= 0) return 1;
  const raw = range / 10;
  const mag = Math.pow(10, Math.floor(Math.log10(raw)));
  const norm = raw / mag;
  const step = norm < 1.5 ? 1 : norm < 3 ? 2 : norm < 7 ? 5 : 10;
  return step * mag;
}

const num = (v: unknown): number | null =>
  v == null || Number.isNaN(Number(v)) ? null : Number(v);
const mul = (v: unknown, k: number): number | null => (num(v) == null ? null : (v as number) * k);
const div = (v: unknown, k: number): number | null => (num(v) == null ? null : (v as number) / k);
function fix(v: unknown, dp: number, missing: string): string {
  const x = num(v);
  return x == null ? missing : x.toFixed(dp);
}
